export const DEVNET_COUNTER_PACKAGE_ID = '0xTODO'
export const MAINNET_COUNTER_PACKAGE_ID = '0xTODO'

export const MODULE_ADDRESS = process.env.NEXT_PUBLIC_MODULE_ADDRESS

export const NETWORK_NAME = process.env.NEXT_PUBLIC_NETWORK_NAME
